---
- name: Check if deploy_initialize_before scripts exist
  local_action: stat path="{{ item }}"
  register: deploy_initialize_before_paths
  with_items: "{{ deploy_initialize_before | default([]) }}"

- include_tasks: "{{ include_path.item }}"
  with_items: "{{ deploy_initialize_before_paths.results }}"
  loop_control:
    loop_var: include_path
  when: include_path.stat.exists
  tags: deploy-initialize-before

- name: Initialize
  deploy_helper:
    current_path: "{{ project_current_path }}"
    path: "{{ project_root }}"
    state: present

- name: Check if deploy_initialize_after scripts exist
  local_action: stat path="{{ item }}"
  register: deploy_initialize_after_paths
  with_items: "{{ deploy_initialize_after | default([]) }}"

- include_tasks: "{{ include_path.item }}"
  with_items: "{{ deploy_initialize_after_paths.results }}"
  loop_control:
    loop_var: include_path
  when: include_path.stat.exists
  tags: deploy-initialize-after
